version: "3"

services:
  wordpress:
    image: wordpress:5.7.2-apache
    restart: 'always'
    volumes:
      - ${APACHE_DOCUMENT_ROOT-./data/html}:/var/www/html
    depends_on:
      - mysql
    restart: 'always'
    ports:
      - "${HOST_MACHINE_PORT}:80"
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  mysql:
    image: mariadb
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  pma:
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    links:
      - mysql
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    image: nginx
    restart: 'always'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    ports:
        - "127.0.0.1:${NGINX_PORT}:80"
    links:
        - wordpress
